
"use client";

import { useEffect, useState } from "react";
import { useFormState } from "react-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useUser } from "@/firebase";
import { requestDeposit } from "@/app/actions";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { Asset } from "@/lib/types";
import { Copy, Check } from "lucide-react";

const depositSchema = z.object({
  assetId: z.string().min(1, "Please select an asset."),
});

type DepositFormValues = z.infer<typeof depositSchema>;

// This would be generated by a real backend wallet service
const generateMockAddress = (symbol: string) => {
    return `${symbol.toLowerCase()}-address-` + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

export function DepositForm({ assets }: { assets: Asset[] }) {
  const { user } = useUser();
  const { toast } = useToast();
  const [state, formAction] = useFormState(requestDeposit, { status: "idle", message: "" });
  const [depositAddress, setDepositAddress] = useState("");
  const [hasCopied, setHasCopied] = useState(false);

  const form = useForm<DepositFormValues>({
    resolver: zodResolver(depositSchema),
    defaultValues: { assetId: "" },
  });

  useEffect(() => {
    if (state.status === 'success') {
      toast({ title: "Address Generated", description: state.message });
      const selectedAsset = assets.find(a => a.id === form.getValues('assetId'));
      if(selectedAsset) {
          setDepositAddress(generateMockAddress(selectedAsset.symbol));
      }
    } else if (state.status === 'error') {
      toast({ variant: "destructive", title: "Error", description: state.message });
      setDepositAddress("");
    }
  }, [state, toast, assets, form]);

  const onCopy = () => {
    if (depositAddress) {
      navigator.clipboard.writeText(depositAddress).then(() => {
        setHasCopied(true);
        setTimeout(() => setHasCopied(false), 2000);
      });
    }
  };

  const handleAssetChange = (assetId: string) => {
      form.setValue('assetId', assetId);
      setDepositAddress(""); // Clear address when asset changes
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Request Deposit</CardTitle>
        <CardDescription>Generate a deposit address for your chosen asset.</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form action={formAction} className="space-y-6">
            <FormField
              control={form.control}
              name="assetId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Asset</FormLabel>
                  <Select onValueChange={handleAssetChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select an asset to deposit" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {assets.map(asset => (
                        <SelectItem key={asset.id} value={asset.id}>
                          {asset.name} ({asset.symbol})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            
            <Button type="submit" className="w-full" disabled={!user}>
              {user ? 'Generate Deposit Address' : 'Please sign in'}
            </Button>
          </form>
        </Form>
        {depositAddress && (
            <div className="mt-6 space-y-4 rounded-lg border bg-muted/50 p-4">
                <p className="text-sm font-medium">Your Deposit Address:</p>
                <div className="relative">
                    <Input readOnly value={depositAddress} className="font-mono pr-10" />
                    <Button
                        size="icon"
                        variant="ghost"
                        className="absolute top-1/2 right-1 h-7 w-7 -translate-y-1/2"
                        onClick={onCopy}
                        aria-label="Copy address"
                    >
                        {hasCopied ? (
                        <Check className="h-4 w-4 text-green-500" />
                        ) : (
                        <Copy className="h-4 w-4" />
                        )}
                    </Button>
                </div>
                <p className="text-xs text-muted-foreground">
                    Only send funds for the selected asset to this address. Sending any other asset may result in the loss of your deposit.
                </p>
            </div>
        )}
      </CardContent>
    </Card>
  );
}
